# WORKING ON NUMPY

In [2]:
#FOR IMPORTING NUMPY
import numpy as np

In [8]:
import sklearn

In [3]:
print("hello world")

hello world


In [5]:
i=45

In [6]:
print(i)

45


In [ ]:
i

In [9]:
i+=1

In [10]:
print(i)

46


In [18]:
#FOR DECLARING NUMPY ARRAY
myarr = np.array([3,6,9,12,15], np.int8)

In [17]:
myarr

array([ 3,  6,  9, 12, 15])

In [19]:
##np.int8 for declaring 8 byte number

In [21]:
myarr = np.array([3,6,9,66777777,15], np.int8)

In [24]:
#ERROR HAS OCCURED AND IT CHANGES TO -79 DUE TO ERROR BECAUSE NO IS VERY BIG AND IT JUST NEEDS 8 BYTES
myarr

array([  3,   6,   9, -79,  15], dtype=int8)

In [38]:
#FOR SINGLE DIMENSION ARRAY
#SINGLRE DIMENSION ARRAY ME COLUMNS NHI HOTI JUST ROWS HOTI H
myarr1 = np.array(([1,2,3,4,5]),np.int64)

In [29]:
myarr1

array([1, 2, 3, 4, 5], dtype=int64)

In [35]:
#ACCESSING INDEX
myarr1[0]

1

In [33]:
#FINDING NO OF ROWS AND COLUMNS IN A SINGLE DIMENSION ARRAY
myarr1.shape

(5,)

In [45]:
#FOR MULTI DIMENSION ARRAY
#[1,2,3,4,5] ye 0 index pr h array k
#[9,10,11,13,14] ye 1 index pr array k
myarr1 = np.array(([[1,2,3,4,5],[9,10,11,13,14]]),np.int64)

In [46]:
myarr1[0,1]

2

In [47]:
myarr1.shape

(2, 5)

In [48]:
myarr1.dtype

dtype('int64')

In [49]:
#TO CHANGE ELEMENTS IN A ARRAY
myarr1[0,1] = 45

In [50]:
myarr1[0,1] 

45

In [52]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [53]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
#SHAPE SHOWS NUMBER OF ROWS AND NO OF COLUMNS
listarray.shape

(3, 3)

In [57]:
#SHOWS TOTAL NO OF ROWS PLUS TOTAL NO OF COLUMNS
listarray.size

9

In [58]:
#ARRAY IS USED FOR DECLARING SETS
np.array({34,24,24})

array({24, 34}, dtype=object)

In [59]:
##FOR CREATING THE ARRAY FOR ZEROS
zeros = np.zeros((3,6))

In [60]:
zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [63]:
##TO GIVE A RANGE OF NUMBERS
rng = np.arange(20)

In [65]:
#RNG IS A NUMPY ARRAY
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [69]:
lspace = np.linspace(1,50,10)

In [70]:
#GIVE LINEARLY SPACED ELEMENTS FROM 1 TO 5,IT SHOULD BE 12
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [71]:
x= [[1,2,3],[4,5,6],[7,8,9]]

In [72]:
ar = np.array(x)

In [73]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
ar.sum(axis=0)

array([12, 15, 18])

In [75]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [77]:
#FOR TRANSPOSING MATRIX
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [79]:
#tell about no of dimensions
ar.ndim

2

In [80]:
#SIZE OF ARRAY
ar.size

9

In [83]:
#FOR SORTING
np4 = ar.argsort()

In [84]:
np4

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [87]:
#for shaping matrix
##for shapping in a single row
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
##for shapping in a multiple rows
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [89]:
##MATRIX OPERATIONS ON NUMPY
ar2 = np.array ([[1,2,4],[2,3,4],[4,5,6]])


In [91]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
ar+ar2

array([[ 2,  4,  7],
       [ 6,  8, 10],
       [11, 13, 15]])

In [93]:
ar*ar2

array([[ 1,  4, 12],
       [ 8, 15, 24],
       [28, 40, 54]])

In [94]:
ar-ar2

array([[ 0,  0, -1],
       [ 2,  2,  2],
       [ 3,  3,  3]])

In [95]:
##for list ot just concatenate the values
[1,2,3]+[4,5,6]

[1, 2, 3, 4, 5, 6]

In [96]:
#for doing sqroot of elements in an array
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [97]:
ar.sum()

45

In [98]:
ar.min()

1

In [100]:
#count non zero elements in an array
np.count_nonzero(ar)

9

In [102]:
#convert it into list
ar.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# LINEAR REGRESSION

In [41]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [42]:
#step 1: Load data
df = pd.read_csv(r'C:\Users\SRK\Downloads\Movie_Revenue_Dataset_Clean.csv - Movie_Revenue_Dataset_Clean.csv.csv')

In [43]:
#step 2:for reading data
df.head()

production_budget  worldwide_gross
0           14000000          1000000
1            7000000          1000000
2            1000000          1000000
3            1700000          1000915
4             800000          1001437

In [44]:
df.shape

(5529, 2)

In [45]:
#Step 3: Splitting the data
X=df.drop('worldwide_gross',axis=1) ##YE INPUT VARIABLES SARE SAVE KRE G TO HMNE OUTPUT VARIABLE KO DROP KRDIA
y=df['worldwide_gross'] ##FOR OUTPUT VARIABLE

print('Shape of X:',X.shape)
print('Shape of Y:',y.shape)

Shape of X: (5529, 1)
Shape of Y: (5529,)


In [46]:
#STEP 3: ABOVE SPLIT DATA KO TEST OR TRAIN ME SPLIT KRNA HA
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=51)

print('Shape of X_train:',X_train.shape)
print('Shape of y_train:',y_train.shape)
print('Shape of X_test:',X_test.shape)
print('Shape of Y_test:',y_test.shape)

Shape of X_train: (4423, 1)
Shape of y_train: (4423,)
Shape of X_test: (1106, 1)
Shape of Y_test: (1106,)


In [47]:
from sklearn.preprocessing import StandardScaler
sc =  StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [48]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
#fit method is used to make the coefficients(Qo,Q1,Q2,Q3) learn
lr.fit(X_train,y_train)


LinearRegression()

In [49]:
lr.coef_

array([49169005.64390941])

In [50]:
#MODEL NE KONSE INTERCEPT VALUE PE LEARN KIYA
lr.intercept_

46736912.96224282

In [51]:
##PEDICTING THE VALUES
#INFORMATION OF SINGLE HOUSE
X_test[0,  : ]

array([0.36619432])

In [52]:
#prediction of a single vale
lr.predict([X_test[0, :]])

array([64742323.46830991])

In [53]:
#prediction of multiple valures of inputs
lr.predict(X_test)

array([64742323.46830991, 39577939.18840452, 15557390.55758572, ...,
       16701226.20667233, 55591638.27561704, 70461501.71374296])

In [54]:
y_test

3805     46982632
2837     31390587
5127      8373585
4130     52287414
2310     25532388
          ...    
3391      4210379
5238     83320000
4756       685780
3100     35228696
3021    335451311
Name: worldwide_gross, Length: 1106, dtype: int64

In [55]:
#TO CHECK THE ACCURACY OF MODEL
lr.score(X_test, y_test)

0.46514516289683694

In [56]:
y_pred = lr.predict(X_test)

In [ ]:
import seaborn as sns
%matplotlib inline

sns.pairplot(x_vars = X,y_vars = y,size = 7, aspect = 0.7, kind = 'reg')




# FOR R2 VALUE,WE FIRST TRAIN THE MODEL.


In [57]:
from sklearn.metrics import r2_score

In [58]:
r2_score(X,y)

-0.5886722889073863

# MISS PORTION OF LINEAR REGRESSION

In [29]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [30]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [31]:
model = LinearRegression()

In [32]:
model.fit(x, y)

LinearRegression()

In [33]:
r_sq = model.score(x, y)

In [34]:
 print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.715875613747954


In [38]:
print(f"intercept: {model.intercept_}")

intercept: 5.633333333333329


In [36]:
print(f"slope: {model.coef_}")

slope: [0.54]


In [37]:
y_pred = model.predict(x)
print(f"predicted response:\n{y_pred}")

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression


plt.figure(figsize=(4, 3))
ax = plt.axes()
ax.scatter(X, y)
ax.plot(X, y)

ax.set_xlabel('x')
ax.set_ylabel('y')

ax.axis('tight')

plt.show()

# LINEAR REGRESSION FROM A SOURCE

In [59]:
from sklearn.linear_model import LinearRegression

#initiate linear regression model
model = LinearRegression()

In [ ]:
#define predictor and response variables
X, y = df[["hours", "prep_exams"]], df.score

#fit regression model
model.fit(X, y)

#calculate R-squared of regression model
r_squared = model.score(X, y)

#view R-squared value
print(r_squared)

0.7175541714105901

# KNN CLASSIFIER

In [61]:
##internet code

In [ ]:
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()

iris.feature_names
iris.target_names

df = pd.DataFrame(iris.data,columns=iris.feature_names)
df.head()

df['target'] = iris.target
df.head()

df[df.target==1].head()

df[df.target==2].head()

df['flower_name'] =df.target.apply(lambda x: iris.target_names[x])
df.head()

df0 = df[:50]
df1 = df[50:100]
df2 = df[100:]

#FOR PLOTTING
import matplotlib.pyplot as plt
%matplotlib inline

plt.xlabel('Sepal Length')
plt.ylabel('Sepal Width')
plt.scatter(df0['sepal length (cm)'], df0['sepal width (cm)'],color="green",marker='+')
plt.scatter(df1['sepal length (cm)'], df1['sepal width (cm)'],color="blue",marker='.')

plt.xlabel('Petal Length')
plt.ylabel('Petal Width')
plt.scatter(df0['petal length (cm)'], df0['petal width (cm)'],color="green",marker='+')
plt.scatter(df1['petal length (cm)'], df1['petal width (cm)'],color="blue",marker='.')

#Train test split
from sklearn.model_selection import train_test_split

X = df.drop(['target','flower_name'], axis='columns')
y = df.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
len(X_train)
len(X_test)

##Create KNN (K Neighrest Neighbour Classifier)

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train, y_train)
knn.score(X_test, y_test)
knn.predict([[4.8,3.0,1.5,0.3]])

##Plot Confusion Matrix(FOR EVALUATION OF CASSIFICATION MATRIX)

from sklearn.metrics import confusion_matrix
y_pred = knn.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
cm

%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sn
plt.figure(figsize=(7,5))
sn.heatmap(cm, annot=True)
plt.xlabel('Predicted')
plt.ylabel('Truth')


##Print classification report for precesion, recall and f1-score for each classes

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))








In [63]:
##MISS CODE

In [64]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
dataset = pd.read_csv(url, names=names)
dataset.head()
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


##FOR EVALUATING ERROR

error = []

# Calculating error for K values between 1 and 40
for i in range(1, 40):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train, y_train)
    pred_i = knn.predict(X_test)
    error.append(np.mean(pred_i != y_test))
    
plt.figure(figsize=(12, 6))
plt.plot(range(1, 40), error, color='red', linestyle='dashed', marker='o',
         markerfacecolor='blue', markersize=10)
plt.title('Error Rate K Value')
plt.xlabel('K Value')
plt.ylabel('Mean Error')

# NAIVES BAYES CLASSIFIER

In [ ]:
#FROM INTERNET
# import libraries
import numpy as np
import pandas as pd
 
"""### Load Dataset"""
 
#load dataset
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()
 
data.data
 
data.feature_names
 
data.target
 
data.target_names
 
# create dtaframe
df = pd.DataFrame(np.c_[data.data, data.target], columns=[list(data.feature_names)+['target']])
df.head()
 
df.tail()
 
df.shape
 
"""### Split Data"""
 
X = df.iloc[:, 0:-1]
y = df.iloc[:, -1]
 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2020)
 
print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

"""
## Naive Bayes Classifier
 
### Import Libraries
"""
 
# import libraries
import numpy as np
import pandas as pd
 
"""### Load Dataset"""
 
#load dataset
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()
 
data.data
 
data.feature_names
 
data.target
 
data.target_names
 
# create dtaframe
df = pd.DataFrame(np.c_[data.data, data.target], columns=[list(data.feature_names)+['target']])
df.head()
 
df.tail()
 
df.shape
 
"""### Split Data"""
 
X = df.iloc[:, 0:-1]
y = df.iloc[:, -1]
 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2020)
 
print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)
 
"""## Train Naive Bayes Classifier Model"""
 
from sklearn.naive_bayes import GaussianNB
 
classifier = GaussianNB()
classifier.fit(X_train, y_train)
 
classifier.score(X_test, y_test)


 


#MISS
import pandas as pd
df=pd.read_csv("titanic.csv")
df.head()
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis="columns",inplace=True)
df.head()
target=df.Survived
target.head()



# KNN REGRESSION

In [ ]:
# Read the file
import pandas as pd
df = pd.read_csv('train.csv')
df.head()

##Impute missing values
df.isnull().sum()
#missing values in Item_weight and Outlet_size needs to be imputed
mean = df['Item_Weight'].mean() #imputing item_weight with mean
df['Item_Weight'].fillna(mean, inplace =True)

mode = df['Outlet_Size'].mode() #imputing outlet size with mode
df['Outlet_Size'].fillna(mode[0], inplace =True)

##Deal with categorical variables and drop the id columns
df.drop(['Item_Identifier', 'Outlet_Identifier'], axis=1, inplace=True)
df = pd.get_dummies(df)


##Create train and test set
from sklearn.model_selection import train_test_split
train , test = train_test_split(df, test_size = 0.3)

x_train = train.drop('Item_Outlet_Sales', axis=1)
y_train = train['Item_Outlet_Sales']

x_test = test.drop('Item_Outlet_Sales', axis = 1)
y_test = test['Item_Outlet_Sales']

##Preprocessing – Scaling the features
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))

x_train_scaled = scaler.fit_transform(x_train)
x_train = pd.DataFrame(x_train_scaled)

x_test_scaled = scaler.fit_transform(x_test)
x_test = pd.DataFrame(x_test_scaled)


##Let us have a look at the error rate for different k values
#import required packages
from sklearn import neighbors
from sklearn.metrics import mean_squared_error 
from math import sqrt
import matplotlib.pyplot as plt
%matplotlib inline

rmse_val = [] #to store rmse values for different k
for K in range(20):
    K = K+1
    model = neighbors.KNeighborsRegressor(n_neighbors = K)

    model.fit(x_train, y_train)  #fit the model
    pred=model.predict(x_test) #make prediction on test set
    error = sqrt(mean_squared_error(y_test,pred)) #calculate rmse
    rmse_val.append(error) #store rmse values
    print('RMSE value for k= ' , K , 'is:', error)
